	chain vm_input {
		iifname "virbr1" udp dport { 53, 67, 123 } accept comment "Allow VM DNS,NTP & DHCP"
		iifname "virbr1" tcp dport { 53, 67 } accept comment "Allow VM DNS and DHCP"
	}

	chain vm_forward {
		iifname "virbr1" accept comment "Allow traffic from VM to WAN"
		iifname "lo" oifname "vibr1" accept comment "allow host to vm"
		oifname "virbr1" ct state { established, related } accept comment "Allow return traffic to VM"
	}

  chain forward {
		type filter hook forward priority filter; policy drop;
		jump vm_forward
	}

  
	chain input {
		type filter hook input priority filter; policy drop;
    ct state invalid drop
    ct state { related, established } accept
    iif "lo" accept
		jump vm_input
	}
